import React, { useState } from 'react';
import { AlertTriangle, ChevronDown, Edit3, Plus, Search, Trash2 } from 'lucide-react';
import { useDashboard } from '../context/DashboardContext';
import { InventoryItem } from '../types';

export const InventoryPage: React.FC = () => {
  const { inventory, updateStock, deleteItem, setIsAddItemModalOpen, showToast } = useDashboard();
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('All');
  const filtered = inventory.filter(item => item.name.toLowerCase().includes(query.toLowerCase()) && (status === 'All' || item.status === status.toLowerCase()));
  const reorder = (item: InventoryItem) => { updateStock(item.id, item.stock + (item.suggestedOrder || Math.ceil(item.minPar - item.stock))); showToast(`Order prepared for ${item.name}`, 'success'); };
  return <div className="max-w-7xl mx-auto space-y-6">
    <header className="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><p className="text-sm font-semibold text-blue-800">Stock control</p><h1 className="text-3xl font-extrabold tracking-tight text-slate-950 mt-1">Inventory Management</h1><p className="text-sm text-slate-500 mt-1">Track raw materials, view status, and manage orders.</p></div><button onClick={() => setIsAddItemModalOpen(true)} className="inline-flex items-center gap-2 rounded-lg bg-blue-900 px-4 py-2.5 text-sm font-bold text-white"><Plus className="w-4 h-4" /> Add item</button></header>
    <div className="flex flex-col sm:flex-row gap-3"><label className="relative flex-1"><Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-400" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search ingredients..." className="w-full rounded-lg border border-slate-200 bg-white py-2.5 pl-9 pr-3 text-sm outline-none focus:border-blue-800" /></label><label className="relative"><select value={status} onChange={e => setStatus(e.target.value)} className="appearance-none rounded-lg border border-slate-200 bg-white py-2.5 pl-3 pr-9 text-sm outline-none"><option>All</option><option>Critical</option><option>Low</option><option>Normal</option></select><ChevronDown className="absolute right-3 top-3 w-4 h-4 text-slate-400 pointer-events-none" /></label></div>
    <div className="flex gap-2 overflow-x-auto">{['Critical', 'Low', 'Normal'].map(item => <span key={item} className={`rounded-full px-3 py-1.5 text-xs font-bold ${item === 'Critical' ? 'bg-red-100 text-red-700' : item === 'Low' ? 'bg-red-50 text-red-600' : 'bg-emerald-50 text-emerald-700'}`}>{item} ({inventory.filter(stock => stock.status === item.toLowerCase()).length})</span>)}</div>
    <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Ingredient</th><th className="px-4 py-3">Category</th><th className="px-4 py-3">On hand</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Expiry</th><th className="px-4 py-3">Recommended order</th><th className="px-4 py-3" /></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(item => <tr key={item.id} className="hover:bg-slate-50"><td className="px-5 py-4 font-bold text-slate-900">{item.name}</td><td className="px-4 py-4 text-slate-500">{item.category}</td><td className="px-4 py-4 font-mono">{item.stock} {item.unit}</td><td className="px-4 py-4"><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase ${item.status === 'critical' ? 'bg-red-100 text-red-700' : item.status === 'low' ? 'bg-red-50 text-red-600' : 'bg-emerald-50 text-emerald-700'}`}>{item.status}</span></td><td className="px-4 py-4 text-slate-500">{item.expiryDate}</td><td className="px-4 py-4">{item.suggestedOrder > 0 ? <button onClick={() => reorder(item)} className="font-bold text-blue-800 hover:underline">{item.suggestedOrder} {item.unit} order</button> : <span className="text-slate-400">-</span>}</td><td className="px-4 py-4"><div className="flex gap-2"><button onClick={() => updateStock(item.id, item.stock)} aria-label={`Edit ${item.name}`} className="text-slate-400 hover:text-blue-800"><Edit3 className="w-4 h-4" /></button><button onClick={() => deleteItem(item.id)} aria-label={`Delete ${item.name}`} className="text-slate-400 hover:text-red-600"><Trash2 className="w-4 h-4" /></button></div></td></tr>)}</tbody></table>{filtered.length === 0 && <div className="p-10 text-center text-sm text-slate-500"><AlertTriangle className="mx-auto mb-2 w-5 h-5" />No ingredients match your search.</div>}</div>
  </div>;
};
