import React from 'react';
import { CalendarClock, Download, FileSpreadsheet, FileText, Filter, Mail, Plus } from 'lucide-react';
import { useDashboard } from '../context/DashboardContext';
import { ReportItem } from '../types';

export const ReportsPage: React.FC = () => {
  const { reports, downloadReport, setIsScheduleReportModalOpen, showToast } = useDashboard();
  const icon = (type: ReportItem['type']) => type === 'CSV' || type === 'XLSX' ? <FileSpreadsheet className="w-5 h-5 text-blue-800" /> : <FileText className="w-5 h-5 text-red-600" />;
  return <div className="max-w-5xl mx-auto space-y-6">
    <header className="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><p className="text-sm font-semibold text-blue-800">Exports and delivery</p><h1 className="text-3xl font-extrabold tracking-tight text-slate-950 mt-1">Reports & Exports</h1><p className="text-sm text-slate-500 mt-1">Generate, view, and download operational reports.</p></div><div className="flex gap-2"><button onClick={() => showToast('Report filters ready', 'info')} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm font-bold text-slate-700"><Filter className="w-4 h-4" /> Filter</button><button onClick={() => setIsScheduleReportModalOpen(true)} className="inline-flex items-center gap-2 rounded-lg bg-blue-900 px-3 py-2.5 text-sm font-bold text-white"><CalendarClock className="w-4 h-4" /> Schedule</button></div></header>
    <section className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden"><div className="px-5 py-4 border-b border-slate-200"><h2 className="font-bold text-slate-950">Available reports</h2></div><div className="divide-y divide-slate-100">{reports.slice(0, 5).map(report => <div key={report.id} className="flex flex-col sm:flex-row sm:items-center gap-4 px-5 py-4"><div className="rounded-lg bg-slate-50 p-3">{icon(report.type)}</div><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold text-slate-900">{report.name.split(' (')[0]}</h3><span className="rounded bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-600">{report.type}</span></div><p className="text-xs text-slate-500 mt-1">{report.desc}</p><p className="text-[11px] text-slate-400 mt-2">Last generated: {report.lastGenerated}</p></div><button onClick={() => downloadReport(report)} className="inline-flex items-center justify-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-blue-800 hover:bg-blue-50"><Download className="w-4 h-4" /> Download</button></div>)}</div></section>
    <div className="grid md:grid-cols-2 gap-4"><button onClick={() => showToast('Custom report builder opened', 'info')} className="rounded-xl border border-dashed border-blue-200 bg-blue-50/50 p-5 text-left"><Plus className="w-5 h-5 text-blue-800" /><h2 className="font-bold text-slate-950 mt-3">Custom report builder</h2><p className="text-xs text-slate-500 mt-1">Select specific metrics and date ranges to create a new template.</p></button><button onClick={() => setIsScheduleReportModalOpen(true)} className="rounded-xl border border-slate-200 bg-white p-5 text-left"><Mail className="w-5 h-5 text-blue-800" /><h2 className="font-bold text-slate-950 mt-3">Scheduled deliveries</h2><p className="text-xs text-slate-500 mt-1">Manage automated email reports sent to stakeholders.</p></button></div>
  </div>;
};
