import React from 'react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { AlertTriangle, ArrowDownRight, Recycle, Scale } from 'lucide-react';
import { BASELINE_METRICS, INGREDIENT_WASTE } from '../data/mockData';
import { formatPeso } from '../utils/currency';

export const WastePage: React.FC = () => {
  const totalWaste = INGREDIENT_WASTE.reduce((sum, item) => sum + item.wasteKg, 0);
  const totalLoss = INGREDIENT_WASTE.reduce((sum, item) => sum + item.costLoss, 0);
  return <div className="max-w-7xl mx-auto space-y-6">
    <header><p className="text-sm font-semibold text-blue-800">Kitchen efficiency</p><h1 className="text-3xl font-extrabold tracking-tight text-slate-950 mt-1">Waste & Spoilage</h1><p className="text-sm text-slate-500 mt-1">Track wasted ingredients, expiry causes, and the financial impact of over-ordering.</p></header>
    <section className="grid grid-cols-1 sm:grid-cols-3 gap-4"><Metric icon={Scale} label="Waste last 30 days" value={`${totalWaste} kg`} note={`Baseline ${BASELINE_METRICS.weeklyWasteKgBaseline} kg / week`} /><Metric icon={ArrowDownRight} label="Current weekly waste" value={`${BASELINE_METRICS.weeklyWasteKgCurrent} kg`} note={`-${BASELINE_METRICS.spoilageRateBaseline - BASELINE_METRICS.spoilageRateCurrent}% spoilage rate`} /><Metric icon={AlertTriangle} label="Estimated loss" value={formatPeso(totalLoss, 0)} note="Expiry, trim, and over-batching" /></section>
    <section className="grid grid-cols-1 xl:grid-cols-[1.2fr_0.8fr] gap-5"><div className="bg-white rounded-xl border border-slate-200 shadow-sm p-5"><h2 className="font-bold text-slate-950">Waste by ingredient</h2><p className="text-xs text-slate-500 mt-1 mb-4">Kilograms recorded by the inventory ledger</p><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={INGREDIENT_WASTE}><CartesianGrid stroke="#e2e8f0" strokeDasharray="3 3" vertical={false} /><XAxis dataKey="ingredient" tick={{ fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis axisLine={false} tickLine={false} /><Tooltip /><Bar dataKey="wasteKg" fill="#DC2626" radius={[4, 4, 0, 0]} name="Waste (kg)" /></BarChart></ResponsiveContainer></div></div><div className="bg-blue-50/60 rounded-xl border border-blue-100 p-5"><div className="flex items-center gap-2"><Recycle className="w-5 h-5 text-blue-800" /><h2 className="font-bold text-slate-950">Waste response</h2></div><p className="text-sm text-slate-600 mt-3">The DSS combines expiry dates, shelf life, forecast demand, and supplier lead times to recommend promotions, prep priorities, or order freezes.</p><div className="mt-5 rounded-lg bg-white border border-blue-100 p-3"><p className="text-xs font-bold text-blue-900">Spoilage alert rule</p><p className="text-xs text-slate-500 mt-1">Items near expiry are escalated to the Insights page for promotional menu suggestions.</p></div></div></section>
    <section className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-slate-50 border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Ingredient</th><th className="px-4 py-3">Waste</th><th className="px-4 py-3">Financial loss</th><th className="px-4 py-3">Cause</th><th className="px-4 py-3">Category</th></tr></thead><tbody className="divide-y divide-slate-100">{INGREDIENT_WASTE.map(item => <tr key={item.ingredient}><td className="px-5 py-4 font-bold text-slate-900">{item.ingredient}</td><td className="px-4 py-4 font-mono">{item.wasteKg} kg</td><td className="px-4 py-4 font-bold text-red-700">{formatPeso(item.costLoss)}</td><td className="px-4 py-4 text-slate-500">{item.reason}</td><td className="px-4 py-4 text-slate-500">{item.category}</td></tr>)}</tbody></table></section>
  </div>;
};

const Metric: React.FC<{ icon: React.ElementType; label: string; value: string; note: string }> = ({ icon: Icon, label, value, note }) => <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-sm"><Icon className="w-5 h-5 text-blue-800" /><p className="text-xs font-bold uppercase tracking-wide text-slate-400 mt-4">{label}</p><p className="text-2xl font-extrabold font-mono text-slate-950 mt-1">{value}</p><p className="text-xs text-slate-500 mt-2">{note}</p></div>;
